#!/usr/bin/env bun

import "zx/globals";
import React, {
  createContext,
  memo,
  useContext,
  useState,
  useEffect,
} from "react";
import { render, Box, Text, useInput, useFocus, Spacer, useStdout } from "ink";

const SHOW_DEV_TOOLS = true;

const useStdoutDimensions = (): [number, number] => {
  const { stdout } = useStdout();
  const [dimensions, setDimensions] = useState<[number, number]>([
    stdout.columns,
    stdout.rows,
  ]);

  useEffect(() => {
    const handler = () => setDimensions([stdout.columns, stdout.rows]);
    stdout.on("resize", handler);
    return () => {
      stdout.off("resize", handler);
    };
  }, [stdout]);

  return dimensions;
};

interface StateContextProps {
  status: string;
  setStatus: (status: string) => void;
}

const StateContext = createContext<StateContextProps>({
  status: "",
  setStatus: () => {},
});

const StateProvider: FC<{ children: React.ReactNode } & StateContextProps> = ({
  children,
  ...props
}) => {
  return (
    <StateContext.Provider value={props}>{children}</StateContext.Provider>
  );
};

interface MessageProps {
  message: string;
}

const Message: FC<MessageProps> = memo(({ message }) => {
  return (
    <Text>
      <Text color="gray">: </Text>
      {message}
    </Text>
  );
});

interface InputProps {
  prompt: string;
  onCommit: (prompt: string) => void;
  onDevMessage: (message: string) => void;
}

const Input: FC<InputProps> = memo(({ prompt, onCommit, onDevMessage }) => {
  const { setStatus } = useContext(StateContext);

  const [value, setValue] = useState("");

  useInput((input, key) => {
    onDevMessage(
      `${input} ${JSON.stringify(key)
        .replace(/"/g, "")
        .replace(/Arrow/g, "")
        .replace(/true/g, "T")
        .replace(/false/g, "F")}`
    );

    if (key.return) {
      setValue("");
      onCommit(value);
    } else if (key.delete) {
      setValue((value: string) => value.slice(0, -1));
    } else if (input === "g" && key.ctrl) {
      setValue("");
    } else {
      setValue((value: string) => value + input);
    }

    setStatus(`Length: ${value.length}`);
  });

  return (
    <Text>
      <Text color="green">{prompt}</Text>
      {value}
    </Text>
  );
});

const App = () => {
  const [columns, rows] = useStdoutDimensions();

  const [status, setStatus] = useState("");

  const [buffer, setBuffer] = useState([]);
  const [devMessage, setDevMessage] = useState("");

  const onCommit = (input: string) => {
    setBuffer([...buffer, input]);
  };

  return (
    <StateProvider status={status} setStatus={setStatus}>
      <Box
        width={columns}
        height={rows}
        minHeight="100%"
        flexDirection="column"
        justifyContent="space-between"
      >
        <Box flexGrow={1} flexDirection="column" height="100%" width="100%">
          {buffer.map((line, index) => (
            <Message key={index} message={line} />
          ))}
          <Input prompt=": " onCommit={onCommit} onDevMessage={setDevMessage} />
        </Box>
        <Spacer />
        <Box>
          <Text>{status}</Text>
        </Box>

        {SHOW_DEV_TOOLS && (
          <Box borderStyle="round" borderColor="gray" gap={1}>
            <Text color="gray">
              {columns} x {rows}
            </Text>
            <Text color="gray">{devMessage}</Text>
          </Box>
        )}
      </Box>
    </StateProvider>
  );
};

console.clear();

const { waitUntilExit } = render(<App />);

await waitUntilExit();

console.clear();
